server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: Lama2005argo
  jpa:
    hibernate.ddl-auto: update


jwt:
  secret: "zM7HwqMZKe1hMfAoDZK6y0LOpmFgBGzptsnkNHlxKIM="
  expiration: 3600000